title: "Naufal Said"
email: naufal.said19@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "/nosaa19.github.io"
# You only need to define your social links here and no need to edit the footer.html
social:
  twitter_username: _
  github_username:  nosaa19
  linkedin_username: naufal.said


sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg

# your google analytics tag goes here
# how to get your analytics tag?
# https://support.google.com/analytics/answer/1008080
google-analytics: XX-000000000-0
resume: /assets/resume.pdf
